processes: list(include('process'), min=1)

process: any( include('receiver'), include('sender'), include('getter'), include('pipeline'), include('filter'), include('admin'), include('auth'))

receiver:
  type: regex('receiver')
  common: include('networkAgentCommon')
  # I'd rather do this, but it is messier than I thought
  # protocol: include('protocol')
  protocol: enum('udp')
  port: include('port')

sender:
  type: regex('sender')
  common: include('networkAgentCommon')
  # I'd rather do this, but it is messier than I thought
  # protocol: include('protocol')
  protocol: enum('udp','ssh')

getter:
  type: regex('getter')
  common: include('networkAgentCommon')
  # I'd rather do this, but it is messier than I thought
  # protocol: include('protocol')
  protocol: enum('ssh')

networkAgentCommon:
  interfaceType: include('interfaceType')
  processInfo: include('processInfo')
  # read or write, depending whether entry or exit
  folder: include('folder')

# I'd rather do this, but it is messier than I thought
# protocol: enum('tcp', 'udp', 'ssh') # protocol varies by agent

# this is a list, but a list as a sequence
# is there always a filter? no, not necessarily
# entry and exit are always required, so create a subtype
# that forces them, while allowing filters to be optional
# This will at least get my schema validated, but will not enforce order
pipeline:
  entry: include('entry')
  filters: list(include('filter'), required=False)
  exit: include('exit')

entry: any(include('receiver'), include('getter'))

# Probably only ever a sender, but maybe folders? TBD...
exit: any(include('sender'))
  #type: any(include('sender'), include('folder'))

# no longer sure about this....
# hmm, if we use filters, there must be at least one,
# but filters are optional - cf pipelineElement above
#filters: list(include('filter'), min=1)

folder:
  path:    include('path')
  folderType:    include('folderType')
  fileTransition:    include('fileTransition', required=False)

filter:
  order:  int() # specify this manually - use this in the generation code....
  processInfo: include('processInfo')
  in: include('in')
  out: include('out')
  err: include('err')
  canExecs: include('canExecs', required=False)

canExecs: list(include('canExec'))

canExec:
  processInfo: include('processInfo')

in: include('folder')

out: include('folder')

err: include('folder')

admin: include('processInfo')

auth: include('processInfo')

processInfo:
  name: str()
  description: str(required=False)
  processType:       include('processType')
  startedBy:       include('startedBy')

startedBy: any(include('user'), include('system'), include('process'))

user:
  userRole: include('role')
  processTransition: include('processTransition', required=False)

system:
  systemTransition: include('initTransition')

# primitives/terminals to be validated
fileTransition:    str() # for now
initTransition:    str() # for now
processTransition: str() # for now

# fairly well understood primitives/terminals
port:          int()
interfaceType: str()  # the SELinux type for the interface
path:          str()  # for now; likely
role:          str()  # an SELinux role
processType:   str()  # the actual SELinux type for the process
folderType:    str()  # the actual SELinux type for the folder

